videos:
  straight_0_left_1:
    waiting_areas:
      - [64, 193]
      - [102, 178]
      - [373, 393]
      - [142, 419]
      - [112, 338]
      - [48, 258]
    turning_left_area:
      - [372, 392]
      - [103, 177]
      - [140, 164]
      - [457, 389]

  straight_0_left_2: &fixed_video
    waiting_straight_area:
      - [146, 455]
      - [58, 314]
      - [63, 229]
      - [102, 220]
      - [372, 436]
    waiting_left_area:
      - [103, 224]
      - [160, 216]
      - [456, 430]
      - [373, 436]

  clear_road: *fixed_video
  straight_1_left_0: *fixed_video
  straight_2_left_0: *fixed_video
  straight_4_left_0: *fixed_video
  straight_6_left_0: *fixed_video
  straight_8_left_0: *fixed_video

  clear_pavement:
    waiting_areas:
      - [23, 1130]
      - [331, 678]
      - [691, 754]
      - [695, 1258]
      - [243, 1262]

  waiting_people:
    waiting_areas:
      - [8, 684]
      - [172, 424]
      - [456, 488]
      - [452, 828]
      - [236, 832]

  walking_people:
    waiting_areas:
      - [8, 684]
      - [172, 424]
      - [456, 488]
      - [452, 828]
      - [236, 832]
