videos:
  arrived_car:
    waiting_areas:
      - [36, 444]
      - [184, 440]
      - [452, 632]
      - [452, 824]
      - [76, 824]

  clear_pavement:
    waiting_areas:
      - [23, 1130]
      - [331, 678]
      - [691, 754]
      - [695, 1258]
      - [243, 1262]

  clear_road:
    waiting_areas:
      - [ 60, 694 ]
      - [ 264, 666 ]
      - [ 768, 1034 ]
      - [ 760, 1246 ]
      - [ 116, 1250 ]

  stop_car:
    waiting_areas:
      - [32, 370]
      - [160, 358]
      - [448, 582]
      - [456, 826]
      - [72, 826]

  traffic_road:
    waiting_areas:
      - [4, 1432]
      - [288, 1052]
      - [720, 1064]
      - [1072, 1600]
      - [1064, 1896]
      - [12, 1892]

  waiting_car:
    waiting_areas:
      - [20, 360]
      - [148, 348]
      - [456, 576]
      - [456, 828]
      - [64, 828]

  waiting_people:
    waiting_areas:
      - [8, 684]
      - [172, 424]
      - [456, 488]
      - [452, 828]
      - [236, 832]

  walking_people:
    waiting_areas:
      - [8, 684]
      - [172, 424]
      - [456, 488]
      - [452, 828]
      - [236, 832]
