canvas:
  width: 200
  height: 200
priority:
  car: 1
  motorcycle: 1
  bicycle: 2
  person: 3
  bus: 4
  truck: 4
models:
  car_west:
    video_source: video/straight_4.mp4
    video_sources:
      clear: video/straight_0.mp4
      busy:
        - video/straight_1.mp4
        - video/straight_4.mp4
        - video/straight_6.mp4
        - video/straight_8.mp4
    places: [170, 325]
    buttons: {button_x: 5, button_y: 360}
    traffic_lights:
      - {x: 380, y: 325, width: 70, height: 190, oriented: 'west_east_straight'}
    tracked_objects: &road
      - car
      - bicycle
      - motorcycle
      - bus
      - truck

  car_east:
    video_source: video/straight_0.mp4
    video_sources:
      clear: video/straight_0.mp4
      busy:
        - video/straight_1.mp4
        - video/straight_4.mp4
        - video/straight_6.mp4
        - video/straight_8.mp4
    places: [1350, 325]
    buttons: {button_x: 1550, button_y: 360}
    traffic_lights:
      - {x: 1250, y: 325, width: 70, height: 190, oriented: 'west_east_straight'}
    tracked_objects: *road

  car_north:
    video_source: video/straight_0_left_0.mp4
    video_sources:
      clear: video/straight_0_left_0.mp4
      busy:
        - video/straight_1_left_0.mp4
        - video/straight_2_left_0.mp4
        - video/straight_4_left_0.mp4
        - video/straight_6_left_0.mp4
        - video/straight_8_left_0.mp4
        - video/straight_0_left_1.mp4
        - video/straight_0_left_2.mp4
    places: [650, 10]
    buttons: {button_x: 850, button_y: 10}
    traffic_lights:
      - {x: 570, y: 50, width: 70, height: 190, oriented: 'north_south_straight'}
      - {x: 470, y: 50, width: 70, height: 190, oriented: 'turning_left_area'}
    tracked_objects: *road

  car_south:
    video_source: video/straight_0_left_0.mp4
    video_sources:
      clear: video/straight_0_left_0.mp4
      busy:
        - video/straight_1_left_0.mp4
        - video/straight_2_left_0.mp4
        - video/straight_4_left_0.mp4
        - video/straight_6_left_0.mp4
        - video/straight_8_left_0.mp4
        - video/straight_0_left_1.mp4
        - video/straight_0_left_2.mp4
    places: [650, 700]
    buttons: {button_x: 850, button_y: 800}
    traffic_lights:
      - {x: 850, y: 600, width: 70, height: 190, oriented: 'north_south_straight'}
      - {x: 950, y: 600, width: 70, height: 190, oriented: 'turning_left_area' }
    tracked_objects: *road

  people_x1y1:
    video_source: video/clear_pavement.mp4
    video_sources:
      clear: video/clear_pavement.mp4
      busy: video/waiting_people.mp4
    places: [170, 10]
    buttons: {button_x: 5, button_y: 60}
    traffic_lights:
      - {x: 380, y: 50, width: 70, height: 130, oriented: 'west_east_straight', with_yellow_color: false}
    tracked_objects: &pavement
      - person

  people_x2y1:
    video_source: video/clear_pavement.mp4
    video_sources:
      clear: video/clear_pavement.mp4
      busy: video/waiting_people.mp4
    places: [1350, 10]
    buttons: {button_x: 1550, button_y: 60}
    traffic_lights:
      - {x: 1250, y: 50, width: 70, height: 130, oriented: 'west_east_straight', with_yellow_color: false}
    tracked_objects: *pavement

  people_x1y2:
    video_source: video/clear_pavement.mp4
    video_sources:
      clear: video/clear_pavement.mp4
      busy: video/waiting_people.mp4
    places: [170, 700]
    buttons: {button_x: 5, button_y: 760}
    traffic_lights:
      - {x: 380, y: 700, width: 70, height: 130, oriented: 'west_east_straight', with_yellow_color: false}
    tracked_objects: *pavement

  people_x2y2:
    video_source: video/clear_pavement.mp4
    video_sources:
      clear: video/clear_pavement.mp4
      busy: video/waiting_people.mp4
    places: [1350, 700]
    buttons: {button_x: 1550, button_y: 760}
    traffic_lights:
      - {x: 1250, y: 700, width: 70, height: 130, oriented: 'west_east_straight', with_yellow_color: false}
    tracked_objects: *pavement
