models:
  car_x1:
    video_source: video/traffic_road.mp4
    places: [170, 325]
    buttons:
      - {button_x: 5, button_y: 360, label: 'Play waiting car', video_path: 'video/waiting_car.mp4'}
      - {button_x: 5, button_y: 390, label: 'Play clear road', video_path: 'video/clear_road.mp4'}
    traffic_light: {x: 380, y: 420, width: 70, height: 190}
    oriented: 'x'

  car_x2:
    video_source: video/waiting_car.mp4
    places: [1350, 325]
    buttons:
      - {button_x: 1550, button_y: 360, label: 'Play waiting car', video_path: 'video/waiting_car.mp4'}
      - {button_x: 1550, button_y: 390, label: 'Play clear road', video_path: 'video/clear_road.mp4'}
    traffic_light: {x: 1250, y: 325, width: 70, height: 190}
    oriented: 'x'

  car_y1:
    video_source: video/clear_road.mp4
    places: [650, 10]
    buttons:
      - {button_x: 850, button_y: 60, label: 'Play waiting car', video_path: 'video/waiting_car.mp4'}
      - {button_x: 850, button_y: 90, label: 'Play clear road', video_path: 'video/clear_road.mp4'}
    traffic_light: {x: 570, y: 170, width: 70, height: 190}
    oriented: 'y'

  car_y2:
    video_source: video/clear_road.mp4
    places: [650, 700]
    buttons:
      - {button_x: 850, button_y: 870, label: 'Play waiting car', video_path: 'video/waiting_car.mp4'}
      - {button_x: 850, button_y: 900, label: 'Play clear road', video_path: 'video/clear_road.mp4'}
    traffic_light: {x: 850, y: 600, width: 70, height: 190}
    oriented: 'y'

  people_x1y1:
    video_source: video/clear_pavement.mp4
    places: [170, 10]
    buttons:
      - {button_x: 5, button_y: 60, label: 'Play clear pavement', video_path: 'video/clear_pavement.mp4'}
      - {button_x: 5, button_y: 90, label: 'Play waiting people', video_path: 'video/waiting_people.mp4'}
    traffic_light: {x: 400, y: 130, width: 70, height: 130, with_yellow_color: false}
    oriented: 'y'

#  people_x2y1:
#    video_source: video/clear_pavement.mp4
#    places: [1350, 10]
#    buttons:
#      - {button_x: 1550, button_y: 60, label: 'Play clear pavement', video_path: 'video/clear_pavement.mp4'}
#      - {button_x: 1550, button_y: 90, label: 'Play waiting people', video_path: 'video/waiting_people.mp4'}
#
#  people_x1y2:
#    video_source: video/clear_pavement.mp4
#    places: [170, 700]
#    buttons:
#      - {button_x: 5, button_y: 760, label: 'Play clear pavement', video_path: 'video/clear_pavement.mp4'}
#      - {button_x: 5, button_y: 790, label: 'Play waiting people', video_path: 'video/waiting_people.mp4'}
#
#  people_x2y2:
#    video_source: video/clear_pavement.mp4
#    places: [1350, 700]
#    buttons:
#      - {button_x: 1550, button_y: 760, label: 'Play clear pavement', video_path: 'video/clear_pavement.mp4'}
#      - {button_x: 1550, button_y: 790, label: 'Play waiting people', video_path: 'video/waiting_people.mp4'}
